# Generated by Django 5.0.6 on 2024-06-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_producto_descripcion_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
    ]
